### ISSUE TITLE
hi,用例中的上传文件是上传到哪的

### ISSUE THREAD

**Issue by xujiewei23** [zyanycall/stressTestPlatform#1]
hi，你好

想问一下，用例管理中，上传文件是上传到哪的，我报了个错误
Resolved exception caused by Handler execution: io.renren.common.exception.RRException: 保存文件异常失败

请问该如何解决呢

**Comment by zyanycall** [comment]
你好。
我在application.yml  中配置了文件上传的位置。
# 性能测试配置
test:
    stress:
        # Jmeter主节点路径
        # 默认是测试报告生成使用
        jmeterHome: D:\software\apache-jmeter-4.0
        # 存放用例的总目录，里面会细分文件存放用例及用例文件
        # Jmeter节点机需要在/etc/bashrc中配置JAVA_HOME，同时source /etc/bashrc生效
        casePath: D:\E\stressTestCases
        # 如果配置了Jmeter脚本启动，则额外开启Jmeter进程运行测试用例脚本及分布式程序。
        # 分布式程序可以取消ssl校验。
        # 同时仅支持Jmeter+InfluxDB+Grafana的实时监控。
        # 如果没有配置Jmeter脚本启动，则使用web本身自带的Jmeter功能。
        # 支持自带的ECharts实时监控。
        # 默认是false，即使用web程序进程来启动Jmeter-master程序。
        useJmeterScript: false

具体位置可以写到这里：
  casePath: D:\E\stressTestCases

未来我计划将用例保存的地点直接上传到数据库的配置中。

感谢使用本平台。

**Comment by zyanycall** [comment]
上传文件等的路径信息，已经可以配置到数据库中了，具体可以查看代码：
key为：
MASTER_JMETER_HOME_KEY
MASTER_JMETER_CASES_HOME_KEY
MASTER_JMETER_USE_SCRIPT_KEY
MASTER_JMETER_REPLACE_FILE_KEY
表为：
sys_config
