### ISSUE TITLE
关于自动监测停止脚本的功能

### ISSUE THREAD

**Issue by smooth00** [zyanycall/stressTestPlatform#10]
能够自动监测停止脚本并停止测试这个功能很好，但是发现不会主动调用stopLocal，而生成报告文件的size写入是在这个方法中的。所以主动停止后的可能会发现报告大小显示为0B，无法生成html报告。

**Comment by zyanycall** [comment]
> 能够自动监测停止脚本并停止测试这个功能很好，但是发现不会主动调用stopLocal，而生成报告文件的size写入是在这个方法中的。所以主动停止后的可能会发现报告大小显示为0B，无法生成html报告。

这个我修复了，你试一下。
