### ISSUE TITLE
如何生产环境部署呢

### ISSUE THREAD

**Issue by andyguo1209** [zyanycall/stressTestPlatform#11]
如何生产环境部署呢？有说明吗？本地环境已经运行OK了

**Comment by zyanycall** [comment]
> > 如何生产环境部署呢？有说明吗？本地环境已经运行OK了
> > 有yml配置，也有pom，打成jar包、war包随你，用jar和dockerfile打成docker image也行，没有说明不就告诉自己灵活使用。

感谢，是这样的。
war包命令可以参考：
![image](https://user-images.githubusercontent.com/13790480/47280430-02832900-d609-11e8-82cf-16d8361c8dec.png)

**Comment by andyguo1209** [comment]
搞定了，谢谢 刚用mac 不太习惯，后来试了一下搞定了，谢谢
