### ISSUE TITLE
linux环境打包，运行报错

### ISSUE THREAD

**Issue by boe1900** [zyanycall/stressTestPlatform#12]
![image](https://user-images.githubusercontent.com/29009023/47474652-8415c980-d84a-11e8-90df-fe682d274321.png)

**Comment by zyanycall** [comment]
我刚刚重新试了一下jar包运行，发现都没有问题。无论在win10上，还是centOS上。
你打包的时候代码没有报错吗？因为这种依赖异常，编译打包时就应该出问题。

**Comment by boe1900** [comment]
我win10打的包在centos上可以，centos上打包没有报错，运行jar包就报如上错误
