### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by pihuzi** [zyanycall/stressTestPlatform#14]
上传脚本启动报错，请问什么问题：
Problem loading XML from:'D:\E\stressTestCases\20181105164939208\case2018110516493990.jmx', missing class com.thoughtworks.xstream.converters.ConversionException: ---- Debugging information ---- cause-exception : com.thoughtworks.xstream.converters.ConversionException cause-message : first-jmeter-class : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67) class : org.apache.jmeter.save.ScriptWrapper required-type : org.apache.jorphan.collections.ListedHashTree converter-type : org.apache.jmeter.save.ScriptWrapperConverter path : /jmeterTestPlan/hashTree/hashTree/hashTree/JavaSampler line number : 29 version : 4.0 r1823414 -------------------------------

**Comment by zyanycall** [comment]
pom文件增加下面一段试试：
                
		<dependency>
			<groupId>org.apache.jmeter</groupId>
			<artifactId>ApacheJMeter_java</artifactId>
			<version>${jmeter.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-slf4j-impl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

目测是这个问题。

**Comment by zyanycall** [comment]
> 上传脚本启动报错，请问什么问题：
> Problem loading XML from:'D:\E\stressTestCases\20181105164939208\case2018110516493990.jmx', missing class com.thoughtworks.xstream.converters.ConversionException: ---- Debugging information ---- cause-exception : com.thoughtworks.xstream.converters.ConversionException cause-message : first-jmeter-class : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67) class : org.apache.jmeter.save.ScriptWrapper required-type : org.apache.jorphan.collections.ListedHashTree converter-type : org.apache.jmeter.save.ScriptWrapperConverter path : /jmeterTestPlan/hashTree/hashTree/hashTree/JavaSampler line number : 29 version : 4.0 r1823414 -------------------------------

目测是缺少Jmeter的其他sampler包，增加如下pom引用段试试：
![image](https://user-images.githubusercontent.com/13790480/47988491-50c21d00-e11d-11e8-8f65-9dd1eda9cac4.png)

**Comment by pihuzi** [comment]
已按最新代码修改pom，还是启动报错
		<dependency>
			<groupId>org.apache.jmeter</groupId>
			<artifactId>ApacheJMeter_jdbc</artifactId>
			<version>${jmeter.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-slf4j-impl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

**Comment by pihuzi** [comment]
如图

**Comment by zyanycall** [comment]
> 已按最新代码修改pom，还是启动报错
> 
> org.apache.jmeter
> ApacheJMeter_jdbc
> ${jmeter.version}
> 
> 
> org.apache.logging.log4j
> log4j-slf4j-impl

可以把脚本发给我      444104595@qq.com

**Comment by zyanycall** [comment]
> org.apache.jmeter ApacheJMeter_jdbc ${jmeter.version} org.apache.logging.log4j log4j-slf4j-impl

你看错了……我是想让你引用java的包……
![image](https://user-images.githubusercontent.com/13790480/48039630-9976e600-e1b0-11e8-9a10-36e1c2aea4db.png)
jdbc的包我代码引用了。
你的jmx文件我尝试了，可以启动。
![image](https://user-images.githubusercontent.com/13790480/48039652-b8757800-e1b0-11e8-93bd-5fbb37c1ffb1.png)

**Comment by pihuzi** [comment]
谢谢，已启动成功！
