### ISSUE TITLE
我脚本里使用了BeanShell Sampler，以shell方式可以启动，但是以java码的方式，会报如下错，是有什么插件没有装吗？

### ISSUE THREAD

**Issue by boe1900** [zyanycall/stressTestPlatform#18]
![image](https://user-images.githubusercontent.com/29009023/48482035-7f8d7100-e84a-11e8-90a7-47192eab3b2c.png)

**Comment by zyanycall** [comment]
我查看了代码，BeanShell Sampler我的环境中是有的，具体是包含在：
![image](https://user-images.githubusercontent.com/13790480/48528004-10566200-e8c8-11e8-87fc-9899723e9909.png)
按理是不会报你这个异常的。

同时我本地尝试了包含BeanShell Sampler在平台运行，也是没有报异常。

1. 请问你这是最新的平台版本代码吗？
2. 脚本可以发给我看看吗？  444104595@qq.com

**Comment by boe1900** [comment]
ApacheJMeter_java包没有引，引入就好了，非常感谢
