### ISSUE TITLE
分布式

### ISSUE THREAD

**Issue by NsirNixp** [zyanycall/stressTestPlatform#19]

**Comment by NsirNixp** [comment]
看代码其实没怎么发现通过jemter_api的方式进行分布式压测的，能说明一下么

**Comment by zyanycall** [comment]
> 看代码其实没怎么发现通过jemter_api的方式进行分布式压测的，能说明一下么

是的，分布式压测启动这里Jmeter的API已经封装的很完全了，仅需要分布式slave节点的ip+port的字符串  +   jmx脚本，就可以进行分布式压测了。
核心代码如下：
DistributedRunner distributedRunner = new DistributedRunner();
distributedRunner.setStdout(System.out); // NOSONAR
distributedRunner.setStdErr(System.err); // NOSONAR
distributedRunner.init(hosts, jmxTree);
engines.addAll(distributedRunner.getEngines());
distributedRunner.start();

内在是使用java的rmi的方式执行slave的压测的，核心都在：
org.apache.jmeter.engine.ClientJMeterEngine    
org.apache.jmeter.engine.RemoteJMeterEngineImpl    类中。

**Comment by NsirNixp** [comment]
get啦， 看源码比较少，看来得多多钻研了

**Comment by NsirNixp** [comment]
<img width="1407" alt="image" src="https://user-images.githubusercontent.com/18341792/48614743-f4d38000-e9c9-11e8-90c4-55a4df298547.png">
说是jmeter4.0的特性，根据网上的方法说『修改server.rmi.ssl.disable=true』 然后就修改了
<img width="819" alt="image" src="https://user-images.githubusercontent.com/18341792/48614846-37955800-e9ca-11e8-9f2a-70d535c5ce35.png">
但是还是报错，所以在部署之前有啥其他操作么

**Comment by zyanycall** [comment]
> <img alt="image" width="1407" src="https://user-images.githubusercontent.com/18341792/48614743-f4d38000-e9c9-11e8-90c4-55a4df298547.png">
> 
> 说是jmeter4.0的特性，根据网上的方法说『修改server.rmi.ssl.disable=true』 然后就修改了
> <img alt="image" width="819" src="https://user-images.githubusercontent.com/18341792/48614846-37955800-e9ca-11e8-9f2a-70d535c5ce35.png">
> 
> 但是还是报错，所以在部署之前有啥其他操作么

改的是本地的jmeter.propertis 文件吗？   改过之后应该不会提示这个吧。

**Comment by zyanycall** [comment]
> > <img alt="image" width="1407" src="https://user-images.githubusercontent.com/18341792/48614743-f4d38000-e9c9-11e8-90c4-55a4df298547.png">
> > 说是jmeter4.0的特性，根据网上的方法说『修改server.rmi.ssl.disable=true』 然后就修改了
> > <img alt="image" width="819" src="https://user-images.githubusercontent.com/18341792/48614846-37955800-e9ca-11e8-9f2a-70d535c5ce35.png">
> > 但是还是报错，所以在部署之前有啥其他操作么
> 
> 改的是本地的jmeter.propertis 文件吗？ 改过之后应该不会提示这个吧。

你这个是分布式节点的连接吗？   那slave也需要改的，或者你配置出来ssl的key。

**Comment by NsirNixp** [comment]
通过jmeter_api的方式执行分布式，报错的位置是服务端， 然后改了本地的jmeter.propertis 文件，代码里说加载本地jmete.propertis
<img width="803" alt="image" src="https://user-images.githubusercontent.com/18341792/48616821-b0e37980-e9cf-11e8-8063-4d2301ec3add.png">
然后我也改了slaver的jmeter.propertis,也都配置了sslkey

**Comment by zyanycall** [comment]
> 通过jmeter_api的方式执行分布式，报错的位置是服务端， 然后改了本地的jmeter.propertis 文件，代码里说加载本地jmete.propertis
> <img alt="image" width="803" src="https://user-images.githubusercontent.com/18341792/48616821-b0e37980-e9cf-11e8-8063-4d2301ec3add.png">
> 然后我也改了slaver的jmeter.propertis,也都配置了sslkey

我查了一下，我本地也没有这个jks文件，同时我也是设置了 server.rmi.ssl.disable=true 的。
看了一下，你应该是使用分布式节点压测的时候报的这个错误。

建议：
1.    你本地设置的Jmeter_home  能否正常使用压测功能  如  ./jmeter -n -t xxxx.jmx  
2.    看看你设置为  server.rmi.ssl.disable=true  的properties 文件  是否是程序真正加载的文件。

**Comment by NsirNixp** [comment]
> > 通过jmeter_api的方式执行分布式，报错的位置是服务端， 然后改了本地的jmeter.propertis 文件，代码里说加载本地jmete.propertis
> > <img alt="image" width="803" src="https://user-images.githubusercontent.com/18341792/48616821-b0e37980-e9cf-11e8-8063-4d2301ec3add.png">
> > 然后我也改了slaver的jmeter.propertis,也都配置了sslkey
> 
> 我查了一下，我本地也没有这个jks文件，同时我也是设置了 server.rmi.ssl.disable=true 的。
> 看了一下，你应该是使用分布式节点压测的时候报的这个错误。
> 
> 建议：
> 
> 1. 你本地设置的Jmeter_home  能否正常使用压测功能  如  ./jmeter -n -t xxxx.jmx
> 2. 看看你设置为  server.rmi.ssl.disable=true  的properties 文件  是否是程序真正加载的文件。

第二点提醒了我，然后我去看了看我的服务，是直接用root用户启动的（而且在/root目录下），然后修改为普通用户临时提升权限的方式启动后，问题没了（至于为啥，部署相关的知识不了解吧）
