### ISSUE TITLE
上传文件时候关联的slave_id没有做表关联，导致上传文件后入库出错

### ISSUE THREAD

**Issue by NsirNixp** [zyanycall/stressTestPlatform#2]
![image](https://user-images.githubusercontent.com/18341792/43623588-96ed25ac-9714-11e8-95e9-d3556d4e9793.png)
![image](https://user-images.githubusercontent.com/18341792/43623601-a3eba99a-9714-11e8-91cd-c0a53faf69cf.png)
![image](https://user-images.githubusercontent.com/18341792/43623652-e3a1e900-9714-11e8-997a-474412fbabfe.png)
保存成功，但是并没有入库，从而导致脚本文件管理获取不到数据

**Comment by zyanycall** [comment]
不是，这是我新增加的字段，在test_stress_case_file  表中。
![image](https://user-images.githubusercontent.com/13790480/43694301-45a567b0-9965-11e8-803c-bf8b652902ee.png)

最近的更新对数据表结构有变化，我知道这很不好，但是没啥办法，当初设计的时候没想过这么复杂。
实在抱歉。

**Comment by zyanycall** [comment]
已经更新脚本，将slave_id 的非null限制取消。

**Comment by iceghosthyb** [comment]
执行脚本的时候，csv文件没自行创建，导致报错:Could not find the TestPlan class!这个文件是要上传上去的吗？？？
