### ISSUE TITLE
打成jar包报错问题

### ISSUE THREAD

**Issue by smooth00** [zyanycall/stressTestPlatform#21]
src/main/java/io/renren/modules/test/utils/StressTestUtils.java这段代码中的
xslFile = ResourceUtils.getFile("classpath:config/jmeter.results.zyanycall.xsl");
在打成jar包后就无法调用了，执行报错。

**Comment by xiasusuxia** [comment]
是读不到jmeter.results.zyanycall.xsl文件，把classpath: 改成 classpath*:就可以了

**Comment by xiasusuxia** [comment]
> src/main/java/io/renren/modules/test/utils/StressTestUtils.java这段代码中的
> xslFile = ResourceUtils.getFile("classpath:config/jmeter.results.zyanycall.xsl");
> 在打成jar包后就无法调用了，执行报错。

是读不到jmeter.results.zyanycall.xsl文件，把classpath: 改成 classpath*:就可以了

**Comment by zyanycall** [comment]
> 是读不到jmeter.results.zyanycall.xsl文件，把classpath: 改成 classpath*:就可以了

> > src/main/java/io/renren/modules/test/utils/StressTestUtils.java这段代码中的
> > xslFile = ResourceUtils.getFile("classpath:config/jmeter.results.zyanycall.xsl");
> > 在打成jar包后就无法调用了，执行报错。
> 
> 是读不到jmeter.results.zyanycall.xsl文件，把classpath: 改成 classpath*:就可以了

感谢提醒和提问。

这个问题已经修改提交了。
我自测没有问题。
希望大家多提issue。
