### ISSUE TITLE
本地节点和分布式节点进行调试所生成的jtl报告不一样

### ISSUE THREAD

**Issue by smooth00** [zyanycall/stressTestPlatform#22]
1、从短时间内（1分钟以内）的测试发现，用本地节点调试生成的jtl报告会达到十几、二十几M，甚至更多，用分布式节点调试生成的jtl报告不到1M。从报告内容来看，本点节点生成调试报告有大量的垃圾数据，应该是来自请求返回的大量数据。说明本地节点和分布式节点调试的效果是不一样的。
2、调试过程查看echarts监控，发现通过本地节点调试和通过分布式节点调式的效果也有差别。
以下提供我的测试脚本，以供参考：
[weixin-Test.zip](https://github.com/zyanycall/stressTestPlatform/files/2656676/weixin-Test.zip)

**Comment by zyanycall** [comment]
> 1、从短时间内（1分钟以内）的测试发现，用本地节点调试生成的jtl报告会达到十几、二十几M，甚至更多，用分布式节点调试生成的jtl报告不到1M。从报告内容来看，本点节点生成调试报告有大量的垃圾数据，应该是来自请求返回的大量数据。说明本地节点和分布式节点调试的效果是不一样的。
> 2、调试过程查看echarts监控，发现通过本地节点调试和通过分布式节点调式的效果也有差别。
> 以下提供我的测试脚本，以供参考：
> [weixin-Test.zip](https://github.com/zyanycall/stressTestPlatform/files/2656676/weixin-Test.zip)

感谢提出问题。
其实这个是已知的问题，调试方法还是有几点需要注意一下的：
1.调试的时候，并发最好少一些，因为jtl文件记录的东西非常多，文件超过几MB真的浏览器打不开。
2.由于当前只能动态修改master主节点的jmeter.properties文件，还不能动态修改slave的配置文件，所以分布式情况下，slave的调试数据传不过来，（slave是默认生成csv文件，jtl的本来就没有）。

未来的方向：
1.将调试结果适当去重（因为有可能返回值故意不重复的，去重困难）。
2.支持动态修改slave的配置文件，达到分布式的调试效果。（性价比不高，主节点的测试调试能够支持绝大多数问题）

目前的方案：
如果分布式的调试造成太多困扰，则如果是分布式情况，提示不支持分布式调试（当前也确实还不支持分布式调试）！

**Comment by smooth00** [comment]
> 感谢提出问题。
> 其实这个是已知的问题，调试方法还是有几点需要注意一下的：
> 1.调试的时候，并发最好少一些，因为jtl文件记录的东西非常多，文件超过几MB真的浏览器打不开。
> 2.由于当前只能动态修改master主节点的jmeter.properties文件，还不能动态修改slave的配置文件，所以分布式情况下，slave的调试数据传不过来，（slave是默认生成csv文件，jtl的本来就没有）。
> 
> 未来的方向：
> 1.将调试结果适当去重（因为有可能返回值故意不重复的，去重困难）。
> 2.支持动态修改slave的配置文件，达到分布式的调试效果。（性价比不高，主节点的测试调试能够支持绝大多数问题）
> 
> 目前的方案：
> 如果分布式的调试造成太多困扰，则如果是分布式情况，提示不支持分布式调试（当前也确实还不支持分布式调试）！

你们这个调试的功能非常好，我是这么想的，从调试功能中可以分离出接口测试的功能，因为接口测试要求比性能测试反馈更多的内容，但是又不需要像调试那样返回过多的调试数据（如果只是为了调试不支持分布式也是可以接受的）。毕竟jmeter除了是性能测试工具，其实也是接口测试工具（强调的是功能性的验证）。

**Comment by toohamster** [comment]
能不能把worker单独抽出来实现?
