### ISSUE TITLE
测试场景组装 打开空白

### ISSUE THREAD

**Issue by xiasusuxia** [zyanycall/stressTestPlatform#23]
**测试场景组装打开展示空白**
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Dec 07 18:05:02 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by xiasusuxia** [comment]
> **测试场景组装打开展示空白**
> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Fri Dec 07 18:05:02 CST 2018
> There was an unexpected error (type=Not Found, status=404).
> No message available

**Comment by zyanycall** [comment]
> **测试场景组装打开展示空白**
> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Fri Dec 07 18:05:02 CST 2018
> There was an unexpected error (type=Not Found, status=404).
> No message available

嗯嗯，测试场景组装是一个不成熟的功能，一直没有上线。
我会将其从菜单中去掉。
