### ISSUE TITLE
不支持BeanShell是吗？

### ISSUE THREAD

**Issue by chongchong01** [zyanycall/stressTestPlatform#26]
1、我本地涉及BeanShell加密的脚本执行是成功的，放在平台上执行失败了；
2、不涉及BeanShell的脚本执行成功了；

**Comment by zyanycall** [comment]
> 1、我本地涉及BeanShell加密的脚本执行是成功的，放在平台上执行失败了；
> 2、不涉及BeanShell的脚本执行成功了；

之前试过，应该是可以支持beanshell的。
请问报什么异常了吗？一般是不报异常的就是支持。
