### ISSUE TITLE
分布式节点启动报错

### ISSUE THREAD

**Issue by lluozh** [zyanycall/stressTestPlatform#27]
分布式节点时，连接失败，服务端报错Neither the JAVA_HOME nor the JRE_HOME environment variable is defined，请问这个可以怎么解决？

**Comment by zyanycall** [comment]
> 分布式节点时，连接失败，服务端报错Neither the JAVA_HOME nor the JRE_HOME environment variable is defined，请问这个可以怎么解决？

你好，
这明显是提示没有Java环境啊……尝试节点机配置一下Java环境变量吧。
