### ISSUE TITLE
任务启动报错 class com.thoughtworks.xstream.converters.ConversionException:

### ISSUE THREAD

**Issue by happybit** [zyanycall/stressTestPlatform#28]
启动用例时遇到下面的报错

从报错上看，和 https://github.com/zyanycall/stressTestPlatform/issues/14 这个issue很像，但我下载的最新代码，pom包已经包含了ApacheJMeter_java，仍然报下面的错:

![unnamed](https://user-images.githubusercontent.com/1286203/50380626-b0619100-06a7-11e9-96a2-b8f4671ea188.png)

脚本已邮件你qq邮箱，谢谢

**Comment by happybit** [comment]
> > 启动用例时遇到下面的报错
> > 从报错上看，和 #14 这个issue很像，但我下载的最新代码，pom包已经包含了ApacheJMeter_java，仍然报下面的错:
> > ![unnamed](https://user-images.githubusercontent.com/1286203/50380626-b0619100-06a7-11e9-96a2-b8f4671ea188.png)
> > 脚本已邮件你qq邮箱，谢谢
> 
> ![image](https://user-images.githubusercontent.com/13790480/50392211-5afcb100-0787-11e9-82d6-280c99505250.png)
> 
> 我Jmeter4.0都打不开这个jmx文件呀，你这是安装什么插件了吧？
> 或者说你是Jmeter什么版本编辑的脚本？

你好！我是用的JMeter 5.0打开的，没问题。

**Comment by happybit** [comment]
@zyanycall 那请问项目pom文件里如何引这些包啊，因为standard也是一个全量的包，不知道对应的具体是哪些。。

**Comment by zyanycall** [comment]
> @zyanycall 那请问项目pom文件里如何引这些包啊，因为standard也是一个全量的包，不知道对应的具体是哪些。。

引用外部包的手段有很多，比如下图这样，添加外部的包。
![image](https://user-images.githubusercontent.com/13790480/50393480-7076d880-0791-11e9-96e7-57797de715b6.png)

但是standard到底有多少jar包，我也不清楚。
建议：
1. 弄清楚为什么要安装这些插件，没必要的话就都干掉，用源生的Jmeter，这样啥事儿没有。
2. 可以查一下这些插件是不是有现成的maven引用，直接添加进去就好。
3. 可以采用目录对比的方式，确定都有哪些包。
4. 如果采用图中的引用外部jar包，要确定一下引用的这些有没有冲突。
5. 也可以直接在项目中添加外部jar包，这根据IDE的不同，添加方式也不太一样，IDEA是在项目管理上可以添加，eclipse的也应该类似。
6. 不太建议直接放到打包好的文件路径如lib下去，因为还是要检查冲突。

最推荐第一条，把插件干掉。

**Comment by happybit** [comment]
> > @zyanycall 那请问项目pom文件里如何引这些包啊，因为standard也是一个全量的包，不知道对应的具体是哪些。。
> 
> 引用外部包的手段有很多，比如下图这样，添加外部的包。
> ![image](https://user-images.githubusercontent.com/13790480/50393480-7076d880-0791-11e9-96e7-57797de715b6.png)
> 
> 但是standard到底有多少jar包，我也不清楚。
> 建议：
> 
> 1. 弄清楚为什么要安装这些插件，没必要的话就都干掉，用源生的Jmeter，这样啥事儿没有。
> 2. 可以查一下这些插件是不是有现成的maven引用，直接添加进去就好。
> 3. 可以采用目录对比的方式，确定都有哪些包。
> 4. 如果采用图中的引用外部jar包，要确定一下引用的这些有没有冲突。
> 5. 也可以直接在项目中添加外部jar包，这根据IDE的不同，添加方式也不太一样，IDEA是在项目管理上可以添加，eclipse的也应该类似。
> 6. 不太建议直接放到打包好的文件路径如lib下去，因为还是要检查冲突。
> 
> 最推荐第一条，把插件干掉。

@zyanycall 我们的插件主要用来收集和查看TPS/RT等指标，如果不用原生的，你这个工具也可以导出来是吗？

**Comment by happybit** [comment]
@zyanycall 好的，那我先删掉那些外部插件试试，多谢多谢！
