### ISSUE TITLE
csv文件要上传上去吗？

### ISSUE THREAD

**Issue by zyanycall** [zyanycall/stressTestPlatform#3]
执行脚本的时候，csv文件没自行创建，导致报错:Could not find the TestPlan class!这个文件是要上传上去的吗？？？

**Comment by zyanycall** [comment]
@iceghosthyb  
csv文件不是上传上去的，是自动生成的。
但是也可以将生成测试报告的功能关闭，如下图：
![image](https://user-images.githubusercontent.com/13790480/45283251-ee2f1500-b50f-11e8-9614-abbfc1ab147a.png)

这样就没有csv文件了。

**Comment by iceghosthyb** [comment]
![image](https://user-images.githubusercontent.com/22002941/45283783-60542980-b511-11e8-8d8e-0ba02e7a7e31.png)
我把测试报告禁止掉了，为啥还是一直报这个错

**Comment by zyanycall** [comment]
哦，我明白你提的问题了。
你是使用的系统的Jmeter 4.0 的api吗？  还是外用的Jmeter?
测试报告的功能需要Jmeter3.0 及以上版本。

然后，是仅仅这一条失败吗？还是测试报告的功能就不好用？

**Comment by iceghosthyb** [comment]
我使用的是Jmeter3.0的， 所有的测试计划都是报这个错。我debug了源代码，报错出现在下面截图的部分，很疑惑，有点搞不懂
![image](https://user-images.githubusercontent.com/22002941/45284327-d4db9800-b512-11e8-8c05-8d31b767952f.png)

**Comment by zyanycall** [comment]
数据库中是会记录csv文件的绝对路径的，你可以查看一下csv文件到底生成没有。
然后可以使用本地的Jmeter 3 试一下，能否生成测试报告。
如果没有生成csv文件，我建议直接使用系统自带的Jmeter4.0的API内核，会生成csv文件的。如果没生成建议debug一下，看看我写的代码是不是哪里报异常了。
如果已经有csv文件，但是使用Jmeter3 无法生成测试报告，建议下载Jmeter4版本的再试一下。如果还是不行，那可能就是Jmeter自身的bug了。

**Comment by iceghosthyb** [comment]
好的，我试下，麻烦啦
