### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ElephantGF** [zyanycall/stressTestPlatform#31]
Cannot determine embedded database driver class for database type NONE

**Comment by zyanycall** [comment]
这问题我也没遇到过，猜测：
1. 你的数据库版本比较高，我这边是5.7的，驱动driver是OK的，你的可能是更高级别版本，需要更换driver的版本。
2. 除了这个提示，还应该有更详细的提示错误，建议再仔细研究一下，或者上网查查类似的问题。

**Comment by ElephantGF** [comment]
谢谢回复！看了一下我的mysql 是5.7.17的，这就很奇怪了，google了很多说是 要在启动类加@SpringBootApplication(exclude =
        {DataSourceAutoConfiguration.class）可是我看你也加了

**Comment by ElephantGF** [comment]
还有一个问题是，项目工程里有一个pom.xml 还有一个pom-war.xml,我用前一个，启动类报编译错，用后一个不报错，但启动的话就报 上面那个数据库的错误 。

**Comment by zyanycall** [comment]
> 还有一个问题是，项目工程里有一个pom.xml 还有一个pom-war.xml,我用前一个，启动类报编译错，用后一个不报错，但启动的话就报 上面那个数据库的错误 。

pom.xml文件是用来本机启动的，pom-war.xml 是用来打war包的。
![image](https://user-images.githubusercontent.com/13790480/53330063-89823e00-3928-11e9-9819-a6b614567267.png)
