### ISSUE TITLE
您好，这些静态变量是拿到代码后，需要自己改其他的值吗？

### ISSUE THREAD

**Issue by qinguanglin381199311** [zyanycall/stressTestPlatform#34]
private static final String JMETER_INSTALLATION_DIRECTORY;
public final static String MASTER_JMETER_HOME_KEY = "";
public final static String MASTER_JMETER_USE_SCRIPT_KEY = "MASTER_JMETER_USE_SCRIPT_KEY";
public final static String MASTER_JMETER_REPLACE_FILE_KEY = "MASTER_JMETER_REPLACE_FILE_KEY";

**Comment by zyanycall** [comment]
是的，在数据库中配置，具体都有注释解释。

**Comment by qinguanglin381199311** [comment]
作者您好，请问在数据库哪张表啊？我刚刚翻完了DB 的表，没有发现配置这些成员变量值的表，谢谢答疑

**Comment by zyanycall** [comment]
-- 数据库中配置性能压测配置信息。key不要变。
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('2', 'MASTER_JMETER_HOME_KEY', 'D:\\software\\apache-jmeter-4.0', '1', '本地Jmeter_home绝对路径');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('3', 'MASTER_JMETER_CASES_HOME_KEY', 'D:\\E\\stressTestCases', '1', '本地保存用例数据的绝对路径，不要随意切换会导致文件找不到错误。');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('4', 'MASTER_JMETER_USE_SCRIPT_KEY', 'false', '1', 'false:在服务器进程内启动Jmeter压测。true:启动Jmeter_home中的命令压测');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('5', 'MASTER_JMETER_REPLACE_FILE_KEY', 'true', '1', '上传文件时，遇到同名文件是替换还是报错，默认是替换为true');

**Comment by qinguanglin381199311** [comment]
明白鸟，谢谢作者，😙么么哒
