### ISSUE TITLE
我能搭建起来了，但是具体操作步骤应该是？

### ISSUE THREAD

**Issue by wangrocky** [zyanycall/stressTestPlatform#35]
除了github的readme中提到的，还需要做哪些配置呢？
我先创建了用例，但是在脚本文件管理中，用例列表展示不出来，一闪而过；接口调用的list是空的，如下：
Request URL: http://localhost:8080/renren-fast/test/stressFile/list?_search=false&nd=1551773502069&limit=50&page=1&sidx=&order=asc&_=1551773501461

![image](https://user-images.githubusercontent.com/6724040/53790542-231da100-3f62-11e9-9f46-8bcdc2b80b7a.png)

我想拿来做jmeter接口自动化测试，通过web集中执行每个人编写的jmeter文件，并汇总展示执行结果

**Comment by wangrocky** [comment]
补充一下当时的录屏，
![default](https://user-images.githubusercontent.com/6724040/53791334-1ef28300-3f64-11e9-9627-91ade7643164.gif)

**Comment by dengmin** [comment]
我跑起来了, 你需要到参数配置里面, 把前面那两个目录参数重新配置一下, 要不能上传文件传不上去的
