### ISSUE TITLE
按web程序进程生成测试报告出现异常

### ISSUE THREAD

**Issue by smooth00** [zyanycall/stressTestPlatform#36]
报错：Class name "org.apache.jmeter.report.processor.graph.impl.TotalTPSGraphConsumer" is not valid
java.lang.ClassNotFoundException: org.apache.jmeter.report.processor.graph.impl.TotalTPSGraphConsumer

**Comment by zyanycall** [comment]
> TotalTPSGraphConsumer

你这个TotalTPSGraphConsumer在Jmeter 4.0 里是哪里都找不到。
生成测试报告是需要读取配置文件的，配置文件在Jmeter_home中。
猜测可能是你的Jmeter_home的版本比较高，导致配置文件中出现了4.0没有的画图实现类。
建议：
可以配置成脚本生成，和原来一样生成测试报告，没变。

**Comment by smooth00** [comment]
> > TotalTPSGraphConsumer
> 
> 你这个TotalTPSGraphConsumer在Jmeter 4.0 里是哪里都找不到。
> 生成测试报告是需要读取配置文件的，配置文件在Jmeter_home中。
> 猜测可能是你的Jmeter_home的版本比较高，导致配置文件中出现了4.0没有的画图实现类。
> 建议：
> 可以配置成脚本生成，和原来一样生成测试报告，没变。

谢谢，确实是用了Jmeter 5.0，我以为不再依赖Jmeter_home了，就没往那想。

**Comment by zyanycall** [comment]
> > > TotalTPSGraphConsumer
> > 
> > 
> > 你这个TotalTPSGraphConsumer在Jmeter 4.0 里是哪里都找不到。
> > 生成测试报告是需要读取配置文件的，配置文件在Jmeter_home中。
> > 猜测可能是你的Jmeter_home的版本比较高，导致配置文件中出现了4.0没有的画图实现类。
> > 建议：
> > 可以配置成脚本生成，和原来一样生成测试报告，没变。
> 
> 谢谢，确实是用了Jmeter 5.0，我以为不再依赖Jmeter_home了，就没往那想。

没事没事。
配置文件还是要读取的，因为配置文件中可以详细设置测试报告的生成指标。

**Comment by skyhack1212** [comment]
屌，5.1遇到一样的问题，已解决。多谢

**Comment by skyhack1212** [comment]
java.io.FileNotFoundException: rmi_keystore.jks (No such file or directory)

新增分布式节点并启用后，执行压测操作，报错---未知异常，请联系管理员。查看日志是上面的报错。
但是我的分布式机器直接执行jmeter-server是没问题的，是哪里没有配置呢？
