### ISSUE TITLE
在性能测试报告管理菜单点击报告名称没有返回报告，提示404

### ISSUE THREAD

**Issue by kuangay** [zyanycall/stressTestPlatform#40]
跳转页面信息返回如下：
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon May 06 16:06:43 CST 2019
There was an unexpected error (type=Not Found, status=404).
No message available
```
然后打开浏览器开发者工具，发现请求的url类似这样：
`http://xxx.xxx.xxx.xxx:8080/renren-fast/testReport/20190506110258275/case20190506110258593/case201905061102585933707/index.html`

> MASTER_JMETER_GENERATE_REPORT_KEY参数配置为false

**Comment by zyanycall** [comment]
能确认一下这个文件是不是真的存在吗？
