### ISSUE TITLE
很好的平台-强烈建议环境做成docker 镜像

### ISSUE THREAD

**Issue by zftest** [zyanycall/stressTestPlatform#43]

**Comment by zyanycall** [comment]
> _No description provided._

这个问题我想了一些，因为我最近也在配置接近10台的master/slave节点机，确实挺费劲。我把我遇到的情况说一下吧，都是在linux上配置的。
1. linux版本低的，比如centOS<2.6.32-431，根本就不支持docker。这版本我真遇到过，就是图稳定。
2. linux版本高的，运维给我的时候就是个空机器，docker是需要我自己安装的（同时升级大量的Linux组件），当时我是需要用docker安装mysql数据库，确实方便。
其实：
1. master最需要的是mysql的配置项（我都考虑使用H2了），其它的配置其实和每个人每个公司的习惯有关系，就比如测试报告的取样时间间隔，是否真的使用SSL分布式加密传输，tomcat内存的配置，是否使用G1GC（JVM调优相关），端口号是否被屏蔽和使用哪个端口号为准，自己修改过平台比如默认是用jmeter 5.1.1版本等等。
2. slave最需要配置的是SSL传输和IP端口号修改，还有调整内存大小。
可以看到，这些都是定制化很强的东西，每个公司和每台机器/虚拟机，情况都是不同的，很难定制化。
同时，slave的配置其实很简单，而master虽然费劲但是定制化很强。
所以，可能也是我懒了吧，这个docker镜像先放一放。

**Comment by smooth00** [comment]
很高兴听到说要使用H2，压测平台如果作为一个工具用mysql是有点浪费，mysql在linux下部署还是偏重量级的，一个包至少一两百M，如果没有docker，安装起来并不省事。

**Comment by zyanycall** [comment]
> _No description provided._

docker镜像前几天玩了一下，未来会试试吧。
