### ISSUE TITLE
pom文件中多了配置，造成打包失败

### ISSUE THREAD

**Issue by muyouyu1314** [zyanycall/stressTestPlatform#46]
pom文件需要注释改段，不然会造成打包失败
        <dependency>-->

**Comment by zyanycall** [comment]
能具体说是哪段吗？
因为我pom文件从2月份开始就没变过了。

**Comment by muyouyu1314** [comment]
<dependency>
            <groupId>io.renren</groupId>
            <artifactId>renren-fast</artifactId>
            <version>1.3.0</version>
        </dependency>

**Comment by muyouyu1314** [comment]
第296行那个

**Comment by zyanycall** [comment]
> 第296行那个

请问能截图来看看吗？我实在没找到。
