### ISSUE TITLE
系统代码报错啦

### ISSUE THREAD

**Issue by pengzhengfa** [zyanycall/stressTestPlatform#49]
<img width="839" alt="微信图片_20190726095656" src="https://user-images.githubusercontent.com/33858082/61920341-d3c92300-af8b-11e9-915d-640891df0c7e.png">

**Comment by pengzhengfa** [comment]
麻烦作者帮我看下

**Comment by zyanycall** [comment]
> 麻烦作者帮我看下

猜测：
1. Jmeter的路径没有配置正确，先修改一下sysconfig表中的Jmeter配置吧。
2. maven引用没成功。

**Comment by pengzhengfa** [comment]
Jmeter的路径,和sysconfig表怎么配置啊,你那个表看不太明白

**Comment by zyanycall** [comment]
> Jmeter的路径,和sysconfig表怎么配置啊,你那个表看不太明白

可以参考一下汉字描述：

-- 数据库中配置性能压测配置信息。key不要变。
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('2', 'MASTER_JMETER_HOME_KEY', 'D:\\software\\apache-jmeter-4.0', '1', '本地Jmeter_home绝对路径');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('3', 'MASTER_JMETER_CASES_HOME_KEY', 'D:\\E\\stressTestCases', '1', '本地保存用例数据的绝对路径，不要随意切换会导致文件找不到错误。');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('4', 'MASTER_JMETER_USE_SCRIPT_KEY', 'false', '1', 'false:在服务器进程内启动Jmeter压测。true:启动Jmeter_home中的命令压测');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('5', 'MASTER_JMETER_REPLACE_FILE_KEY', 'true', '1', '上传文件时，遇到同名文件是替换还是报错，默认是替换为true');
INSERT INTO `sys_config` (`id`, `key`, `value`, `status`, `remark`) VALUES ('6', 'MASTER_JMETER_GENERATE_REPORT_KEY', 'true', '1', 'true:本地web程序进程生成测试报告，可以多线程并发生成。false:使用Jmeter_home中的命令生成测试报告。');
