### ISSUE TITLE
测试报告原始文件找不到

### ISSUE THREAD

**Issue by pengzhengfa** [zyanycall/stressTestPlatform#50]
![Uploading 1.png…]()
作者,你好,这个是少什么东西啦

**Comment by zyanycall** [comment]
> 作者,你好,这个是少什么东西啦

图片没刷出来啊

**Comment by pengzhengfa** [comment]
解决啦




在2019年07月29日 10:38，zyanycall 写道：

作者,你好,这个是少什么东西啦

图片没刷出来啊

**Comment by zyanycall** [comment]
> 解决啦 在2019年07月29日 10:38，zyanycall 写道： 作者,你好,这个是少什么东西啦 图片没刷出来啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

好的~
