### ISSUE TITLE
性能测试报告管理页面的添加时间比实际时间多8小时

### ISSUE THREAD

**Issue by zhouzhou9243** [zyanycall/stressTestPlatform#51]
性能测试报告管理页面的添加时间比实际时间多8小时
我查了数据库，数据库的时间没问题，不知道是什么原因

**Comment by zyanycall** [comment]
> 性能测试报告管理页面的添加时间比实际时间多8小时
> 我查了数据库，数据库的时间没问题，不知道是什么原因

8小时这个时间区间很特殊，因为中国时间是在东八区，相对于格林尼治时间正好是早了8小时。
猜测你们环境的时区配置可能有些问题。

我们前端显示的时间是直接根据数据库时间来的，代码并没有做处理。

**Comment by zhouzhou9243** [comment]
我想问下，前端的代码有做开源么，能提供一个地址么？

**Comment by zyanycall** [comment]
> 我想问下，前端的代码有做开源么，能提供一个地址么？

项目没有做前后端分离，前端代码本身就在项目里。

**Comment by zhouzhou9243** [comment]
好的，谢谢啦
