### ISSUE TITLE
有办法往不同的Jmeter节点传不同的参数么？

### ISSUE THREAD

**Issue by zhouzhou9243** [zyanycall/stressTestPlatform#55]
我想请问下，这个程序有办法往不同的Jmeter节点传不同的参数么，像-Jnodename=1这种

**Comment by zyanycall** [comment]
多谢使用平台。
答：目前平台没有提供这种功能。

**Comment by liangjinwen** [comment]
本地使用jmeter压测，经常都会用到参与传递到压测脚本中，希望日后能支持

**Comment by houshuo521** [comment]
触发压测的是哪个api呢？没有找到呢
