### ISSUE TITLE
分布式节点使用同一份csv文件时的困惑

### ISSUE THREAD

**Issue by jojo201808** [zyanycall/stressTestPlatform#56]
jmx脚本里有两个请求，一个是登录，另外一个是下单（因下单首先要登录），设置并发30，登录的数据来自csv文件，只登录一次，下单采用循环策略。
两个节点一起跑，通过查看数据库看下单用户，发现下单用户的数量在30和60 之间。
困惑：
节点一与节点二在读取csv的时候是同一份文件吗？还是各自取各自文件，如果是各自取各自的文件，那下单用户的数量应该是30哇。如果不是各自跑，感觉应该是60。

**Comment by zyanycall** [comment]
分布式节点会使用各自的文件。
一般来讲，登录的数据需要做拆分，比如节点1的CSV文件中是用户ID 1-30的数据 ， 节点2的CSV文件中是用户ID 31-60 的数据。
建议，直接使用master做压力，CSV直接用户ID 1-60 即可。

**Comment by jojo201808** [comment]
感谢回复，另外还有一个问题，同一个jmx脚本是否只支持一份参数化文件？假如使用两份文件后，在脚本自动执行完成停止时，另一份参数化文件不能关闭，导致平台的执行出现问题。

**Comment by zyanycall** [comment]
> 感谢回复，另外还有一个问题，同一个jmx脚本是否只支持一份参数化文件？假如使用两份文件后，在脚本自动执行完成停止时，另一份参数化文件不能关闭，导致平台的执行出现问题。

如果按你这么描述，应该是个bug，希望能提出来异常看看。
