### ISSUE TITLE
新增分布式节点并正常启用后，压测执行脚本，点击启动报错

### ISSUE THREAD

**Issue by skyhack1212** [zyanycall/stressTestPlatform#58]
报错：java.io.FileNotFoundException: rmi_keystore.jks (No such file or directory)

新增分布式节点并启用后，执行压测操作，报错---未知异常，请联系管理员。查看日志是上面的报错。
但是我的分布式机器直接执行jmeter-server是没问题的，是哪里没有配置吗？还是哪里配置错了？

**Comment by liangjinwen** [comment]
我这边也是遇到跟@skyhack1212一样的问题。我尝试了使用平台启动的分布式服务，在本地连接分布式服务进行压测是正常的，唯独平台压测则报出java.io.FileNotFoundException: rmi_keystore.jks (No such file or directory)的错误

**Comment by zyanycall** [comment]
> 报错：java.io.FileNotFoundException: rmi_keystore.jks (No such file or directory)
> 
> 新增分布式节点并启用后，执行压测操作，报错---未知异常，请联系管理员。查看日志是上面的报错。
> 但是我的分布式机器直接执行jmeter-server是没问题的，是哪里没有配置吗？还是哪里配置错了？

Jmeter 默认master 和 slave 之间，是需要SSL通信的，即加密通信。但是这个可以关掉。
因为我们一般都是内网，不存在窃取请求内容等安全性问题，还有SSL加密解密的过程会带来性能损耗。
所以一般都是关闭的。具体关闭的方式，日志中已经提示：server.rmi.ssl.disable is set to 'true' 这个配置在master的jmeter.properties 文件中，slave中也有一个。 改成true即可。

**Comment by zyanycall** [comment]
> 我这边也是遇到跟@skyhack1212一样的问题。我尝试了使用平台启动的分布式服务，在本地连接分布式服务进行压测是正常的，唯独平台压测则报出java.io.FileNotFoundException: rmi_keystore.jks (No such file or directory)的错误

同上。
