### ISSUE TITLE
运行带参数化文件的脚本时，运行一次后，后续的所有脚本再执行都报错

### ISSUE THREAD

**Issue by tianjinbaoo** [zyanycall/stressTestPlatform#62]
如图：
<img width="998" alt="粘贴的图形-1" src="https://user-images.githubusercontent.com/21972034/76917776-6a719800-68ff-11ea-8d44-c4556f944e4b.png">
点全部停止后再执行脚本又可执行，怀疑带参数化文件脚本执行完毕后未关闭文件

**Comment by tianjinbaoo** [comment]
![image](https://user-images.githubusercontent.com/21972034/76917894-c0464000-68ff-11ea-89d3-e88b36d2b55c.png)
修改代码，加入.closeFiles()后临时解决该问题。希望作者看一下具体原因

**Comment by zyanycall** [comment]
> 如图：
> <img alt="粘贴的图形-1" width="998" src="https://user-images.githubusercontent.com/21972034/76917776-6a719800-68ff-11ea-8d44-c4556f944e4b.png">
> 点全部停止后再执行脚本又可执行，怀疑带参数化文件脚本执行完毕后未关闭文件

你好，看到了你的修改，不过这样修改会导致环境中所有的文件都被关闭，这种方案会让同时进行的带参数化文件的脚本，互相影响并出现问题的。
能给我看一下你们是什么脚本吗，我自测 csv Data set config 没出现问题。
我之前程序中是有处理的，但是覆盖的肯定没有大家遇到的全面。
感谢感谢。

**Comment by tianjinbaoo** [comment]
确实没深入查看过代码，是我不够严谨了。
修改成这样应该就没问题了
![image](https://user-images.githubusercontent.com/21972034/77296574-e0706780-6d22-11ea-8b7d-f51364233d0d.png)
然后，测试脚本
[test.zip](https://github.com/zyanycall/stressTestPlatform/files/4368008/test.zip)

**Comment by tianjinbaoo** [comment]
> > 如：
> > 点全部停止后再执行脚本又重新，怀疑带参数化文件脚本执行完成后未关闭文件
> > <img alt="粘贴的图形-1" width="998" src="https://user-images.githubusercontent.com/21972034/76917776-6a719800-68ff-11ea-8d44-c4556f944e4b.png">
> 
> 你好，看到了你的修改，不过这样修改会导致环境中所有的文件都被关闭，这种方案随之同时进行的带参数化文件的脚本，互相影响并出现问题的。
> 能给我看一下你们是什么脚本吗，我自测csv数据集配置没出现问题。
> 我之前程序中是有处理的，但是覆盖的肯定没有大家遇到的全面。
> 感谢。

确实没深入查看过代码，是我不够严谨了。
修改成这样应该就没问题了
![](https://user-images.githubusercontent.com/21972034/77296574-e0706780-6d22-11ea-8b7d-f51364233d0d.png)
然后，测试脚本
[test.zip](https://github.com/zyanycall/stressTestPlatform/files/4368022/test.zip)

**Comment by zyanycall** [comment]
> > > 如：
> > > 点全部停止后再执行脚本又重新，怀疑带参数化文件脚本执行完成后未关闭文件
> > > <img alt="粘贴的图形-1" width="998" src="https://user-images.githubusercontent.com/21972034/76917776-6a719800-68ff-11ea-8d44-c4556f944e4b.png">
> > 
> > 
> > 你好，看到了你的修改，不过这样修改会导致环境中所有的文件都被关闭，这种方案随之同时进行的带参数化文件的脚本，互相影响并出现问题的。
> > 能给我看一下你们是什么脚本吗，我自测csv数据集配置没出现问题。
> > 我之前程序中是有处理的，但是覆盖的肯定没有大家遇到的全面。
> > 感谢。
> 
> 确实没深入查看过代码，是我不够严谨了。
> 修改成这样应该就没问题了
> ![](https://user-images.githubusercontent.com/21972034/77296574-e0706780-6d22-11ea-8b7d-f51364233d0d.png)
> 然后，测试脚本
> [test.zip](https://github.com/zyanycall/stressTestPlatform/files/4368022/test.zip)

文件我看了，我本机测试也重现了问题。问题在于参数化文件放置的位置，我一般都是放在测试计划的下级，是全局的，你放置的是脚本自己独立使用的。
我的代码中，会找不到这个参数化文件。
那么如果我找不到，你的上面的代码，就不会发生作用。
问题还是需要修复的，我这边会看看。

**Comment by tianjinbaoo** [comment]
> > > > 如：
> > > > 点全部停止后再执行脚本又重新，怀疑带参数化文件脚本执行完成后未关闭文件
> > > > <img alt="粘贴的图形-1" width="998" src="https://user-images.githubusercontent.com/21972034/76917776-6a719800-68ff-11ea-8d44-c4556f944e4b.png">
> > > 
> > > 
> > > 你好，看到了你的修改，不过这样修改会导致环境中所有的文件都被关闭，这种方案随之同时进行的带参数化文件的脚本，互相影响并出现问题的。
> > > 能给我看一下你们是什么脚本吗，我自测csv数据集配置没出现问题。
> > > 我之前程序中是有处理的，但是覆盖的肯定没有大家遇到的全面。
> > > 感谢。
> > 
> > 
> > 确实没深入查看过代码，是我不够严谨了。
> > 修改成这样应该就没问题了
> > ![](https://user-images.githubusercontent.com/21972034/77296574-e0706780-6d22-11ea-8b7d-f51364233d0d.png)
> > 然后，测试脚本
> > [test.zip](https://github.com/zyanycall/stressTestPlatform/files/4368022/test.zip)
> 
> 文件我看了，我本机测试也重现了问题。问题在于参数化文件放置的位置，我一般都是放在测试计划的下级，是全局的，你放置的是脚本自己独立使用的。
> 我的代码中，会找不到这个参数化文件。
> 那么如果我找不到，你的上面的代码，就不会发生作用。
> 问题还是需要修复的，我这边会看看。

好的，那就辛苦作者修复一下
