### ISSUE TITLE
MASTER_JMETER_USE_SCRIPT_KEY = false时，额外的jmeter插件jar包应该放在哪个目录下

### ISSUE THREAD

**Issue by fxsheng1020** [zyanycall/stressTestPlatform#7]
MASTER_JMETER_USE_SCRIPT_KEY = false, 
这种情况下运行jmx文件，总是报下面这个错误，应该是/lib/ext下缺少websocket对应的jar文件导致的。
我想问的是，我该把jar文件放在哪里？我 把它放在MASTER_JMETER_HOME_KEY下面的/lib/ext是没用的，本机运行也没出错，但通过这个平台的网页上执行就不行。

---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:67)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jorphan.collections.ListedHashTree
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/hashTree/eu.luminis.jmeter.wssampler.OpenWebSocketSampler
line number         : 139
version             : 4.0 r1823414
-------------------------------

**Comment by zyanycall** [comment]
请问使用的最新的更新吗？前两天更新了一下，可以加载/lib/ext下的functions了。

**Comment by smooth00** [comment]
websocket的jar包可以通过pom.xml添加依赖，我就是这样实现websocket的测试
