### ISSUE TITLE
dubbo插件化如何支持

### ISSUE THREAD

**Issue by cmcccc** [zyanycall/stressTestPlatform#70]
这个对 dubbo插件化支持么？

**Comment by zyanycall** [comment]
回答晚了不好意思。
平台支持引入3方的jar包。然后我自己之前手打了2.7.4的duboo-jmeter插件的jar包。发送给你吧。
未来这个jar包也可以加入到项目中，不过最近dubbo的更新很快，2.7.4 可能还不稳定。2.7.7 貌似兼容性还不好（没有实证，同事反馈）。
包其中删除了和平台重复的东西，主要是google 的相同的引用的类，还有日志相关的打印。

[jmeter-plugins-dubbo-2.7.4-4platform.jar.zip](https://github.com/zyanycall/stressTestPlatform/files/4862601/jmeter-plugins-dubbo-2.7.4-4platform.jar.zip)

**Comment by zyanycall** [comment]
> 这个对 dubbo插件化支持么？

maven打包可以参考：
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <webResources>
                        <resource>
                            <directory>${project.basedir}/lib</directory>
                            <targetPath>WEB-INF/lib</targetPath>
                            <includes>
                                <include>**/*.jar</include>
                            </includes>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>

**Comment by zyanycall** [comment]
> 这个对 dubbo插件化支持么？

maven 打包可以参考：
![image](https://user-images.githubusercontent.com/13790480/86329575-eefee100-bc78-11ea-8f66-9f3e72b12f16.png)
