### ISSUE TITLE
hi，你好大神，请问，前端的源码能给下吗，我看前端是编译好的。多谢了

### ISSUE THREAD

**Issue by zhulibin2012** [zyanycall/stressTestPlatform#73]

**Comment by zyanycall** [comment]
你好，前端的代码就在项目中，比如这里：stressTestPlatform/src/main/resources/views/modules/test/stressTest.html

**Comment by zhulibin2012** [comment]
请问，有没有重构后的前端代码？我想二次开发，发现前端不是前后分离，而且用的是iframe



---原始邮件---
发件人: "zyanycall"<notifications@github.com&gt;
发送时间: 2020年7月2日(周四) 下午3:32
收件人: "zyanycall/stressTestPlatform"<stressTestPlatform@noreply.github.com&gt;;
抄送: "zhulibin2012"<1821945535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zyanycall/stressTestPlatform] hi，你好大神，请问，前端的源码能给下吗，我看前端是编译好的。多谢了 (#73)




 
你好，前端的代码就在项目中，比如这里：stressTestPlatform/src/main/resources/views/modules/test/stressTest.html

**Comment by zyanycall** [comment]
项目可以做到前后端分离，你直接把前端的这些代码拿出去重新部署也是可以的。整体的前端框架血肉也是vue的。
但是你问现成的有没有，那我这里没有，这部分你要二次开发，还是需要你自己来实现工作量。


> 请问，有没有重构后的前端代码？我想二次开发，发现前端不是前后分离，而且用的是iframe
> […](#)
> ---原始邮件--- 发件人: "zyanycall"<notifications@github.com&gt; 发送时间: 2020年7月2日(周四) 下午3:32 收件人: "zyanycall/stressTestPlatform"<stressTestPlatform@noreply.github.com&gt;; 抄送: "zhulibin2012"<1821945535@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [zyanycall/stressTestPlatform] hi，你好大神，请问，前端的源码能给下吗，我看前端是编译好的。多谢了 (#73) 你好，前端的代码就在项目中，比如这里：stressTestPlatform/src/main/resources/views/modules/test/stressTest.html — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by zhulibin2012** [comment]
好的，谢谢



---原始邮件---
发件人: "zyanycall"<notifications@github.com&gt;
发送时间: 2020年7月4日(周六) 中午1:25
收件人: "zyanycall/stressTestPlatform"<stressTestPlatform@noreply.github.com&gt;;
抄送: "zhulibin2012"<1821945535@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [zyanycall/stressTestPlatform] hi，你好大神，请问，前端的源码能给下吗，我看前端是编译好的。多谢了 (#73)




 
项目可以做到前后端分离，你直接把前端的这些代码拿出去重新部署也是可以的。整体的前端框架血肉也是vue的。
 但是你问现成的有没有，那我这里没有，这部分你要二次开发，还是需要你自己来实现工作量。
  
请问，有没有重构后的前端代码？我想二次开发，发现前端不是前后分离，而且用的是iframe
 …
 ---原始邮件--- 发件人: "zyanycall"<notifications@github.com&gt; 发送时间: 2020年7月2日(周四) 下午3:32 收件人: "zyanycall/stressTestPlatform"<stressTestPlatform@noreply.github.com&gt;; 抄送: "zhulibin2012"<1821945535@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [zyanycall/stressTestPlatform] hi，你好大神，请问，前端的源码能给下吗，我看前端是编译好的。多谢了 (#73) 你好，前端的代码就在项目中，比如这里：stressTestPlatform/src/main/resources/views/modules/test/stressTest.html — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
