### ISSUE TITLE
关于参数化文件的路径问题

### ISSUE THREAD

**Issue by smooth00** [zyanycall/stressTestPlatform#8]
总体上挺好用的。就是Jmeter4.0引用的参数文件路径，用jmeter4.0保存后会变成反斜杠“\”，这在linux下是不识别的。所以建议上传脚本文件时能做个统一处理，以适应linux下执行（省去手动修改脚本的麻烦）。
或者提供个上传jmx脚本参数化文件的界面，就强制把参数文件放到和执行脚本相同的目录下，以相对路径的方式调用参数文件也行。

**Comment by zyanycall** [comment]
参数化文件是可以上传的，并且默认就是放到和执行脚本相同的目录下，你可以再试一试。

**Comment by smooth00** [comment]
> 参数化文件是可以上传的，并且默认就是放到和执行脚本相同的目录下，你可以再试一试。

试了可以上传，只是不支持csv格式的上传。一般参数化文件是txt或cxv格式

**Comment by zyanycall** [comment]
哦，因为我自己是仅用txt一种格式的参数化文件就好了。
我印象中，csv 和 txt 对于Jmeter的不同，仅仅是文件名的不同。
所以默认就上传txt格式的就好了，仅仅是一种格式。

**Comment by zyanycall** [comment]
> > 哦，因为我自己是仅用txt一种格式的参数化文件就好了。
> > 我印象中，csv 和 txt 对于Jmeter的不同，仅仅是文件名的不同。
> > 所以默认就上传txt格式的就好了，仅仅是一种格式。
> 
> 关于文件格式不应该控制太多，因为有时候发送的请求是带附件的，比如图片或WORD文件，这些文件也属于用例的一部分，需要同步到各个节点。

你说的有道理。

我目前确实没遇到过上传附件的测试。
后续我看看将这个限制去掉。

**Comment by zyanycall** [comment]
> > 哦，因为我自己是仅用txt一种格式的参数化文件就好了。
> > 我印象中，csv 和 txt 对于Jmeter的不同，仅仅是文件名的不同。
> > 所以默认就上传txt格式的就好了，仅仅是一种格式。
> 
> 关于文件格式不应该控制太多，因为有时候发送的请求是带附件的，比如图片或WORD文件，这些文件也属于用例的一部分，需要同步到各个节点。

上传文件后缀名的限制我去掉了。你试一下。
